# Generated by Django 3.0.14 on 2021-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(default=''),
        ),
    ]
